#!/bin/sh

brew tap homebrew/services
brew tap caskroom/cask

brew cask install google-chrome
brew cask install iterm2
brew cask install google-drive
brew cask install atom
brew cask install skype
brew cask install java
brew cask install alfred
brew cask install dash

echo 'remember to run "brew cask cleanup" to remove installation package'
gem_install_or_update 'ru'
gem_install_or_update 'pulsar'

brew install 'mysql'
brew install 'htop'
brew install 'rbenv-aliases'
brew install 'rbenv-default-gems'
brew install 'fish'
brew install 'hub'
brew install 'wget'
brew install 'phantomjs'
brew install 'elasticsearch'
brew install 'pwgen'
