#!/usr/bin/env sh

echo "Change osx settings"
sudo -v


echo "Automatically hide and show the Dock"
defaults write com.apple.dock autohide -bool true


echo "Finder: show hidden files by default"
defaults write com.apple.finder AppleShowAllFiles -bool true

echo "Use current directory as default search scope in Finder"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
